"""Write src/cues.js from cues.json so picture and sound share one timing source."""
import json, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
cues = json.load(open(os.path.join(root, "cues.json")))
cues = {k: v for k, v in cues.items() if not k.startswith("_")}
with open(os.path.join(root, "src", "cues.js"), "w") as f:
    f.write("// Generated by tools/sync-cues.py from cues.json. Do not edit by hand.\n")
    f.write("window.CUES = " + json.dumps(cues, indent=2) + ";\n")
print(f"{len(cues)} cues")
